# kol-theme: linkarzu — linkarzu-colors palette (dotfiles-latest).
background            #0D1116
foreground            #ebfafa
cursor                #f94dff
selection_background  #314154
selection_foreground  #ebfafa
url_color             #04d1f9

color0  #141b22
color1  #f16c75
color2  #37f499
color3  #f1fc79
color4  #1682ef
color5  #987afb
color6  #04d1f9
color7  #a5afc2
color8  #314154
color9  #f16c75
color10 #37f499
color11 #f1fc79
color12 #5fa9f4
color13 #949ae5
color14 #19dfcf
color15 #ebfafa
